#	$NetBSD: Makefile,v 1.24 2005/12/11 12:21:25 christos Exp $

INCSDIR= /usr/include/dev/ic

# Install only includes which are used by userland
INCS = athioctl.h bt8xx.h hd44780var.h icp_ioctl.h icpreg.h isp_ioctl.h\
 lptioc.h lptreg.h mlxio.h mlxreg.h rrunnerreg.h rrunnervar.h wdcreg.h\
 wi_ieee.h

.include <bsd.kinc.mk>
